### ISSUE TITLE
Cmap ignores platform/encoding

### ISSUE THREAD

**Issue by mooman219** [RazrFalcon/ttf-parser#10]
You're ignoring the encoding ID but accepting a Unicode `char` as the lookup. This is incorrect behavior. If the encoding is some windows code page instead, and you lookup the Unicode 'a', whatever you get back is worthless. If you do get a mapping for it, it's _definitely_ not for the letter a. 

It's likely that fonts that use non-unicode encodings are rare in the wild, but this library will silently do the wrong thing as it stands.

**Comment by RazrFalcon** [comment]
You're right. The TrueType documentation is a bit scarce on details. I will fix it.

**Comment by RazrFalcon** [comment]
Should be fixed now. I hope that the current behavior is the correct one.
