### ISSUE TITLE
[Question] How can I enumerate all GlyphIds in Face?

### ISSUE THREAD

**Issue by shi-yan** [RazrFalcon/ttf-parser#102]
I can't find any info regarding how to enumerate all glyphs in a Face?

I want to dump all characters from a font, but I don't find a way to do it.

Thanks!

**Comment by RazrFalcon** [comment]
This would be:

```rust
for subtable in face.tables().cmap.unwrap().subtables {
    subtable.codepoints(|c| println!("{}", c));
}
```

Note that a "character" is a very abstract term in TrueType. The `codepoints` method will return `u32`, which could be a Unicode codepoint, but might not be. If you care only about Unicode, add `subtable.is_unicode()` check.

**Comment by shi-yan** [comment]
Thank you very much!
