### ISSUE TITLE
f32 has too little precision for offsets

### ISSUE THREAD

**Issue by laurmaedje** [RazrFalcon/ttf-parser#104]
The [commit], which moved CFF dictionary argument from i32 to f32, breaks outlining for very large fonts. The reason is that some of the private dict offsets are so big that a roundtrip through f32 changes them. This could be fixed simply by switching that part to f64 as it can represent every i32 losslessly. 

I encountered the problem with Noto Serif CJK SC, glyph id 20785. Before the commit, outlining worked and after it, `outline_glyph` returns `None`.

[commit]: https://github.com/RazrFalcon/ttf-parser/commit/44d8c8b90caabc754f67ad0fda1b61290a44b6a7

**Comment by RazrFalcon** [comment]
Makes sense. Will fix it.

**Comment by RazrFalcon** [comment]
@laurmaedje Please check if it worked.

**Comment by laurmaedje** [comment]
Works.
