### ISSUE TITLE
When parsing a regular font (not a collection) the index is ignored

### ISSUE THREAD

**Issue by Pietrek14** [RazrFalcon/ttf-parser#105]
It should return `FaceParsingError::FaceIndexOutOfBounds` when reading from an index different from 0 instead.

An example code that represents what I'm talking about:
```rust
let data = FONT;

assert_eq!(fonts_in_collection(&data), None);
assert_eq!(
    Face::parse(&data, 1).unwrap_err(),
    FaceParsingError::FaceIndexOutOfBounds
);
```

Right now the second assertion fails.

**Comment by RazrFalcon** [comment]
Well, I guess so. It's not that important honestly, but sure, could be improved.

**Comment by Pietrek14** [comment]
Made a pull request (#106) that will resolve this issue when merged.

**Comment by Pietrek14** [comment]
@RazrFalcon I don't want to rush you, but do you know how long it might take for these changes to reach the crates.io version? I need them to implement [font collection support in Bevy](https://github.com/bevyengine/bevy/issues/5773).

**Comment by RazrFalcon** [comment]
Done.

I'm still not sure why do rely on this behaviour in the first place, but fine.
