### ISSUE TITLE
Add essential links to README

### ISSUE THREAD

**Issue by Skaldebane** [RazrFalcon/ttf-parser#112]
Hi there! I would suggest you add the relevant crates.io and docs.rs links to the project's README, because it'll make getting started with the library faster and easier, rather than having to search again for the library on crates.io, and then try to figure out where are the docs.

I could do this if you wish, but I thought you'd know the proper style and language to use.

Thanks in advance!

**Comment by Skaldebane** [comment]
My bad, I just noticed that they all exist in the tiny buttons on top. Sorry for disturbing!

**Comment by RazrFalcon** [comment]
No worries.
