### ISSUE TITLE
Question about parser.rs

### ISSUE THREAD

**Issue by Skaldebane** [RazrFalcon/ttf-parser#114]
Hi there! I'm currently writing a port of this library in Kotlin (kind of, it's heavily inspired by it), and I stumbled across this `impl` block in parser.rs:

```rust
impl FromData for () {
    const SIZE: usize = 0;

    #[inline]
    fn parse(_: &[u8]) -> Option<Self> {
        Some(())
    }
}
```

It looks initially like a useless block of code, but it's probably there for a reason. I couldn't find any usages for it in other code.

I hope you can clarify a bit what is this implementation for, and what purpose does it serve.

Thanks in advance!

**Comment by RazrFalcon** [comment]
It used by generic code and means "parse nothing". 

https://github.com/RazrFalcon/ttf-parser/blob/eb6823889302cc55d40ae09c583c5f51324bdf44/src/aat.rs#L40

**Comment by Skaldebane** [comment]
Ahh now I see. Thanks a lot for the explanation!
