### ISSUE TITLE
Serde feature

### ISSUE THREAD

**Issue by kazcw** [RazrFalcon/ttf-parser#117]
I'm working on an application that needs to be able to serialize/deserialize information identifying a font and its glyphs (we pre-compute some glyph data for faster rendering).

Currently, that requires something like this:
```rust
    let width = match variation.width {
        Width::UltraCondensed => "UltraCondensed",
        Width::ExtraCondensed => "ExtraCondensed",
        Width::Condensed => "Condensed",
        Width::SemiCondensed => "SemiCondensed",
        Width::Normal => "Normal",
        Width::SemiExpanded => "SemiExpanded",
        Width::Expanded => "Expanded",
        Width::ExtraExpanded => "ExtraExpanded",
        Width::UltraExpanded => "UltraExpanded",
    };
```

If you were to sprinkle in a few `#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]` it could save us a lot of manual serialization. In particular, we need to serialize `ttf_parser::{Weight, Width, Style, GlyphId}`--and I'd expect any application that precomputes glyph atlases to have similar needs.

**Comment by RazrFalcon** [comment]
There are no point in using `serde` with `ttf-parser`. And even if we add `serde`, then we would need to support all the types, which is absurd. Adding `serde` support just for 4 out of hundreds of types seems weird to me.

Out of scope. Use new type wrappers.
