### ISSUE TITLE
The direction of outline contour?

### ISSUE THREAD

**Issue by shi-yan** [RazrFalcon/ttf-parser#119]
Hello there,

I'm sorry, this is not a bug report, but I don't know the discussion channel.

I'm implementing a font renderer based on ttf-parser, however, I ran into an issue. My code is a vector-based renderer. To render a glyph, I need to know the inside and the outside of a glyph contour.

I don't know where this is officially documented, I eyeballed the direction by conducting a few experiments. 

Based on my observation, the outline direction is clockwise, whereas counter clock-wise means a hole.

This seems to work well for the otf font file I'm testing. But for a ttf file, it seems to be the opposite, the count clock-wise seems to be the outline, and. a clock-wise contour seems to be a hole.

After realizing the contour direction is not universal, I want to ask what the most reliable way to know the direction of the contour is. 

Thank you!

I saw some very old discussions here without any conclusion:

https://groups.google.com/g/comp.fonts/c/jysddVs06XM?pli=1

for my case, I'm using a special way of rendering with some preprocessing on the glyph's geometry, I need to know the orientation.

**Comment by RazrFalcon** [comment]
Hi! I actually never implemented a font renderer myself, so I cannot answer your question. But I'm aware that outline directions are quite random.

I would suggest asking people who actually implemented renderers on top of ttf-parser like [fontdue](https://github.com/mooman219/fontdue) and [ab-glyph](https://github.com/alexheretic/ab-glyph).

**Comment by shi-yan** [comment]
Thank you so much!

Yesterday, I examined the source code of three.js which supports the rendering of text using geometry

https://github.com/mrdoob/three.js/blob/8400dc53eff51b434ae965edefa387e7695f9e42/src/extras/core/ShapePath.js#L61

I realized that they also use some heuristics to determine the outline direction and match holes with the outlines.

**Comment by shi-yan** [comment]
I realized a thing. The otf file has a cff table instead of a glyf table.

So I guess the orientation is determined by which table the outline is defined.
