### ISSUE TITLE
parse_char_string_width does not take subroutines into account

### ISSUE THREAD

**Issue by Victor-N-Suadicani** [RazrFalcon/ttf-parser#124]
The function `parse_char_string_width` does not seem to take subroutines into account. I know it's not public but I was trying to adapt it to parse with in some charstrings as part of some other application. However, I get wrong results because it returns `None` if it encounters a call to a subroutine, rather than actually calling the subroutine.

**Comment by RazrFalcon** [comment]
Do you have a font that stores width in a subroutine? That's a surprise. But I guess it's technically allowed. Can you send me this font?

**Comment by Victor-N-Suadicani** [comment]
Hi @RazrFalcon just wondering if you're looking into this or if I need to come up with a solution myself? Just want to avoid any potential double-work :)

**Comment by RazrFalcon** [comment]
I will look into it on weekends.

**Comment by RazrFalcon** [comment]
Should be fixed. Please test it.

**Comment by Victor-N-Suadicani** [comment]
It seems to work, thanks!

**Comment by RazrFalcon** [comment]
Published 0.19.1
