### ISSUE TITLE
Vertical bearings does not exist when calling `glyph_ver_side_bearings`

### ISSUE THREAD

**Issue by psuong** [RazrFalcon/ttf-parser#146]
```rust
let face = Face::parse(include_bytes!("..\\..\\UbuntuMonoNerdFontPropo-Regular.ttf"), 0).unwrap();
                                                                                                   
let face_height = face.height();
info!("Units per EM: {}", face.units_per_em());
info!("Face Height: {}", face_height);
                                                                                                   
for c in String::from_str("ABC").unwrap().chars() {
    let glyph_id = face.glyph_index(c).unwrap();                        
    let horizontal_bearing = face.glyph_hor_side_bearing(glyph_id).unwrap();
    match face.glyph_ver_side_bearing(glyph_id) {
        Some(vertical_bearing) => { info!("Vertical Bearing: {}", vertical_bearing); },
        None => info!("Not found")
    };
}
```
I have the above piece of code and I'm trying to fetch the vertical bearings from the font. When using `face.glyph_ver_side_bearing(glyph_id)`, there typically isn't any value so I'm often logging "Not found!". I'm trying to understand why a font wouldn't have the vertical bearings for a letter and what I would need to do in order to get the vertical bearings.

I'm currently using UbuntuMonoNerdFontPropo-Regular.ttf from the nerd font [repo](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/UbuntuMono/Regular/UbuntuMonoNerdFontPropo-Regular.ttf).

The crate version I'm using is: ttf-parser: 0.20.0.

**Comment by RazrFalcon** [comment]
Vertical bearing and advance are only used by vertical fonts. Yours is probably not the one.

You can try checking the presence of the `vmtx` table via `face.tables().vmtx.is_some()`

**Comment by psuong** [comment]
Oh I see. So I was basing my knowledge from the LearnOpenGL Text Rendering and this is how they defined bearings. I didn't realize that vertical bearings was for vertical fonts and assumed it was equivalent to bearings-y in the following image.

![glyph](https://github.com/RazrFalcon/ttf-parser/assets/9100688/0e1beec2-2063-4102-9c93-1a74a8bf6808)

I pretty much want all that info from the image pasted above, so I may have to reexplore the APIs tonight and retrieve the correct info. If there's a guide visually on what the API retrieves that would be helpful, if not I can figure it out

**Comment by RazrFalcon** [comment]
From your picture:

- bearingX is `face.glyph_hor_side_bearing()`
- bearingY is not present in TrueType fonts, but you could try `face.ascender()` instead or guess/calculate it manually from the glyph's bbox
- width is `face.glyph_bounding_box(id).unwrap().width()`
- height is `face.glyph_bounding_box(id).unwrap().height()`
- advance is `face.glyph_hor_advance()`

**Comment by psuong** [comment]
Thanks, I'll play around with the APIs tonight. Closing this issue.
