### ISSUE TITLE
Write support?

### ISSUE THREAD

**Issue by jrmuizel** [RazrFalcon/ttf-parser#15]
It would be interesting to have a replacement for https://github.com/khaledhosny/ots that was written in Rust. To do that we'd need the ability to write out a parsed font.

**Comment by RazrFalcon** [comment]
Writing is out of scope.

1. I don't need it.
1. It's a pretty complex task. Easier than parsing, but still.
1. It should be done as a separate crate.

**Comment by phughk** [comment]
Chiming in, as there is a use case: games and game engines (in particular rust agb library) use fonts for 8x8 tile mapping. So the input is 256 8x8 tiles, and that gets loaded as a TTF using `include_font!`. Other use cases may be scenarios where you want tile rendering but don't want to do full-blown tile rendering.

In my case, I am probably going to use a tool like https://chevyray.dev/blog/creating-175-fonts

Thanks for making this library!

**Comment by RazrFalcon** [comment]
@phughk you can try using https://github.com/googlefonts/fontations as well.
