### ISSUE TITLE
Support a check for when a glyph has no outline, ie is invisible

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#21]
During glyph layout (in [glyph_brush_layout](https://github.com/alexheretic/glyph-brush/tree/master/glyph-brush-layout)) I check if a glyph is invisible or not which can impact whether a word can fit into a line or not.

This check is currently done by see if the glyph has a bounding box or not, which is fast for the ttf fonts that are currently supported. Looking forward to using .otf this will no longer be a generally fast method. 

Is there a quick way of checking this in general for .otf?

Another related idea is to switching the full compute `OutlineBuilder` with an `OutlineIterator`. If we had that presumably it would be possible to call: 
```rust
let invisible = g.outline_iter().next().is_none()
```

**Comment by RazrFalcon** [comment]
>Is there a quick way of checking this in general for .otf?

AFAIK, no. You could try using `glyph_hor_advance`.

>Another related idea is to switching the full compute OutlineBuilder with an OutlineIterator. 

Pull-based iterator will be way slower and way harder to implement. Also, checking only the first point is not enough.

**Comment by alexheretic** [comment]
> Also, checking only the first point is not enough.

Isn't it? These glyphs would have no outline, so the iterator would have no _move_to_, _line_to_, etc items. 

In any case it was just a thought. I'll look into other ideas.

**Comment by RazrFalcon** [comment]
>Isn't it?

Here are some examples:

```
M 0 0 M 0 0
M 0 0 L 0 0
M 0 0 C 0 0 0 0 0 
M 0 0 Z
```

etc.

**Comment by alexheretic** [comment]
Aha I see, thanks for the examples!
