### ISSUE TITLE
Comparision / code sharing with Allsorts

### ISSUE THREAD

**Issue by Shnatsel** [RazrFalcon/ttf-parser#24]
https://github.com/yeslogic/allsorts seems to implement its own TTF parsing. It would be interesting to compare it with ttf-parser. Perhaps there are also code sharing opportunities.

**Comment by RazrFalcon** [comment]
https://www.reddit.com/r/rust/comments/dytdtu/announcing_the_allsorts_font_shaping_engine/f83re0r/

At this moment, ttf-parser supports way more TrueType tables. The only exceptions are GSUB and GPOS, which will be added later.
