### ISSUE TITLE
Providing a get_glyph_extents like API

### ISSUE THREAD

**Issue by ebraminio** [RazrFalcon/ttf-parser#26]
Something equivalent to `hb_font_get_glyph_extents` from ttf-parser would be nice so I can use in benchmarking, there is `ttfp_get_glyph_{hor,ver}_{advance,side_bearing}` which I guess won't be good enough for comparison to that API.

**Comment by RazrFalcon** [comment]
I don't like complex methods. There are too many ways you can implement this and it will be too confusing for a user.

You can easily write a wrapper for this.

**Comment by ebraminio** [comment]
> I don't like complex methods.

Sure

> There are too many ways you can implement this and it will be too confusing for a user.

Yes please, how can I achieve it?

**Comment by RazrFalcon** [comment]
Can you link the `hb_font_get_glyph_extents` in the harfbuzz? I can't find it because of `hb_font_funcs_t`...

**Comment by ebraminio** [comment]
Here it is https://github.com/harfbuzz/harfbuzz/blob/82545c5e2ba2067f2eb117c7358ed6d5b50ca942/src/hb-ot-font.cc#L178-L201

**Comment by RazrFalcon** [comment]
Thanks. Found it. Qt Creator can't open hb properly, which annoys me a lot...

Looks like this method is very hb-specific. This is how it implemented in rustybuzz:

```c++
hb_bool_t hb_ot_get_glyph_extents(hb_font_t *font, void *font_data, hb_codepoint_t glyph, hb_glyph_extents_t *extents)
{
    hb_glyph_bbox_t param;
    const auto ret = rb_ot_get_glyph_bbox(font->ttf_parser, glyph, font->x_ppem, &param);
    if (ret) {
        if (param.min_x >= param.max_x) {
            extents->width = 0;
            extents->x_bearing = 0;
        } else {
            extents->x_bearing = font->em_scalef_x(param.min_x);
            extents->width = font->em_scalef_x(param.max_x - param.min_x);
        }
        if (param.min_y >= param.max_y) {
            extents->height = 0;
            extents->y_bearing = 0;
        } else {
            extents->y_bearing = font->em_scalef_y(param.max_y);
            extents->height = font->em_scalef_y(param.min_y - param.max_y);
        }
    }

    // TODO Hook up side-bearings variations.
    return ret;
}
```

```rust
#[no_mangle]
pub extern "C" fn rb_ot_get_glyph_bbox(ttf_parser_data: *const ffi::rb_ttf_parser_t, glyph: u32, mut x_ppem: u32,
                                       extents: *mut ffi::hb_glyph_bbox_t) -> i32 {
    let font = ttf_parser_from_raw(ttf_parser_data);
    let glyph_id = GlyphId(u16::try_from(glyph).unwrap());

    if x_ppem == 0 {
        x_ppem = std::u16::MAX as u32;
    }

    if let Some(img) = font.glyph_raster_image(glyph_id, x_ppem as u16) {
        // HarfBuzz also supports only PNG.
        if img.format == ttf_parser::RasterImageFormat::PNG {
            let scale = font.units_per_em().unwrap() as f32 / img.pixels_per_em as f32;
            unsafe {
                *extents = ffi::hb_glyph_bbox_t {
                    x_min: (img.x as f32 * scale).round() as i16,
                    y_min: (img.y as f32 * scale).round() as i16,
                    x_max: ((img.x as f32 + img.width as f32) * scale).round() as i16,
                    y_max: ((img.y as f32 + img.height as f32) * scale).round() as i16,
                };
            }

            return 1;
        }
    }

    match font.glyph_bounding_box(glyph_id) {
        Some(bbox) => unsafe {
            *extents = ffi::hb_glyph_bbox_t {
                x_min: bbox.x_min,
                y_min: bbox.y_min,
                x_max: bbox.x_max,
                y_max: bbox.y_max,
            };

            1
        }
        _ => 0,
    }
}
```

So in short, I guess you can use `ttfp_get_glyph_bbox` for benchmarks. It not exactly the same, since `ttf-parser` doesn't care about font size, but still.

**Comment by ebraminio** [comment]
Oh sorry for not founding it, thanks!

**Comment by ebraminio** [comment]
Ok, something quickly revealed on numbers https://github.com/harfbuzz/harfbuzz/pull/2510 `ttfp_get_glyph_bbox` apparently doesn't consider for variation, can that be fixed you think?

**Comment by RazrFalcon** [comment]
It does. You have to use `ttfp_set_variation` beforehand.

**Comment by ebraminio** [comment]
Hmm, I am applying https://github.com/harfbuzz/harfbuzz/blob/2e49be7977aee689aab1cc458e8b20be9df36dd1/perf/perf-extents.hh#L47 but unlike https://github.com/harfbuzz/harfbuzz/blob/2e49be7977aee689aab1cc458e8b20be9df36dd1/perf/perf-draw.hh#L117 I don't see the difference somehow :/

**Comment by RazrFalcon** [comment]
Are you testing gvar or CFF2? Because for gvar, `ttfp_get_glyph_bbox` ignores variation for some reason. Try using `ttfp_outline_glyph` instead. It also returns a bbox.

**Comment by RazrFalcon** [comment]
Looks like a `ttf-parser` bug. And what is more interesting, is that it doesn't affect hb tests at all.

**Comment by ebraminio** [comment]
> Are you testing gvar or CFF2? Because for gvar, ttfp_get_glyph_bbox ignores variation for some reason. Try using ttfp_outline_glyph instead. It also returns a bbox.

Thanks, will use in the meanwhile

> Looks like a ttf-parser bug. And what is more interesting, is that it doesn't affect hb tests at all.

Correct, maybe not lots of var tests, a fix would be very nice. Thanks

**Comment by RazrFalcon** [comment]
Fixed.

**Comment by ebraminio** [comment]
Fix is confirmed, thank you very much!

In case you want to test also,

```
meson build -Dexperimental_api=true -Dbenchmark=true -Dexperimental_api=true -Doptimization=2 && ninja -Cbuild && build/perf/perf
```

on top of https://github.com/harfbuzz/harfbuzz/pull/2510

glyf numbers are a bit worrying, maybe this shouldn't be applied until a coordinate is given anyway.

```
extents/glyf - ot - Comfortaa                        23618 ns      23595 ns      28663
extents/glyf - ft - Comfortaa                       659447 ns     658750 ns       1054
extents/glyf - tp - Comfortaa                      1353911 ns    1352579 ns        511
```

**Comment by RazrFalcon** [comment]
Does *Comfortaa* a variable font?

**Comment by ebraminio** [comment]
Yes, but coordinates weren't given on that case.

**Comment by RazrFalcon** [comment]
1. `ttf-parser` doesn't check for default var coordinates right now. 
1. `ttf-parser` doesn't support phantom points, like hb. Therefore it always outlines the whole glyph.

So this is an expected result. I will create corresponding issues.

**Comment by ebraminio** [comment]
Also there is HVAR/VVAR https://github.com/harfbuzz/harfbuzz/issues/1389#issuecomment-650710660 not all the fonts have it but would be nice if implemented here also.

**Comment by RazrFalcon** [comment]
Implemented where? In `ttfp_get_glyph_bbox`? There are separate methods for that. I don't what adding to much logic on top of TrueType tables.

**Comment by ebraminio** [comment]
oh, that's ok
