### ISSUE TITLE
[CFF] INDEX count overflow + missing local subroutines.

### ISSUE THREAD

**Issue by TakWolf** [RazrFalcon/ttf-parser#31]
original issues is :
https://github.com/alexheretic/ab-glyph/issues/10

**Comment by TakWolf** [comment]
[font link](https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansSC.zip).

```rust
fn main() {
    let font = ttf_parser::Font::from_data(include_bytes!("../SourceHanSansSC-Regular.otf"), 0).unwrap();

    let glyph_index = dbg!(font.glyph_index('A').unwrap());

    dbg!(font.outline_glyph(glyph_index, &mut OutlinePrinter));
}

struct OutlinePrinter;
impl ttf_parser::OutlineBuilder for OutlinePrinter {
    fn move_to(&mut self, x: f32, y: f32) {
        eprintln!("move_to {} {}", x, y);
    }
    fn line_to(&mut self, x: f32, y: f32) {
        eprintln!("line_to {} {}", x, y);
    }
    fn quad_to(&mut self, x1: f32, y1: f32, x: f32, y: f32) {
        eprintln!("quad_to {} {} {} {}", x1, y1, x, y);
    }
    fn curve_to(&mut self, x1: f32, y1: f32, x2: f32, y2: f32, x: f32, y: f32) {
        eprintln!("curve_to {} {} {} {} {} {}", x1, y1, x2, y2, x, y);
    }
    fn close(&mut self) {
        eprintln!("close");
    }
}
```

Output:
```
[src/main.rs:6] font.glyph_index('A').unwrap() = GlyphId(34)
[src/main.rs:8] font.outline_glyph(glyph_index, &mut OutlinePrinter) = None
```

_Originally posted by @alexheretic in https://github.com/alexheretic/ab-glyph/issues/10#issuecomment-657213165_

**Comment by ebraminio** [comment]
Correct, some otf fonts are bitmap fonts, and some won't work correctly without hinting support which both are unrelated in this case, this however should show something like

![image](https://user-images.githubusercontent.com/833473/87280141-0ce50500-c507-11ea-90c0-581486f0e8e1.png)

This is another library result, haven't check ttf-parser result yet, if is there any issue guess should be easy to resolve also.

**Comment by RazrFalcon** [comment]
Yes, `ttf-parser` doesn't allow CFF Index with 0xFFFF values. I will look up how this case is handled in other libraries.

**Comment by RazrFalcon** [comment]
This font is technically malformed, but since it made by Adobe, who actually wrote the CFF spec - I'm confused.

**Comment by RazrFalcon** [comment]
Also, `ttf-parser` couldn't find local subroutines for some reason. So I guess it will take a while to fix all the issues related to this font.
