### ISSUE TITLE
Global metrics of bounding box

### ISSUE THREAD

**Issue by leoyanggit** [RazrFalcon/ttf-parser#32]
First of all I'm excited about this project especially it is wasm friendly! I'm wondering if we have API that can return the global `bbox` like FreeType2 does: https://www.freetype.org/freetype2/docs/tutorial/step2.html, section 3 Global Metrics of `bbox`.

**Comment by RazrFalcon** [comment]
This is not implemented yet, but can be easily done.

**Comment by leoyanggit** [comment]
I'm new to this library. can you please show me which part of the code? I can probably try to implement it.

**Comment by RazrFalcon** [comment]
It's pretty non-trivial, actually. I will do this myself.

**Comment by RazrFalcon** [comment]
Turns out it was very easy.

**Comment by leoyanggit** [comment]
Thanks! It works great.
