### ISSUE TITLE
bug: ttf width is not parsed correctly

### ISSUE THREAD

**Issue by zimond** [RazrFalcon/ttf-parser#35]
in `os2.rs#width()`, due to the default number in Rust is i32, here `Stream::read_at` will read 4 bytes instead of the length of width (which is u16, 2 bytes), leading to width never correctly parsed

**Comment by RazrFalcon** [comment]
Nice catch. Would you mind sending a pull request?

**Comment by RazrFalcon** [comment]
I've even had tests for this and they are passing because testing for a default value...
