### ISSUE TITLE
Why ttf_parser::Face need a lifetime?

### ISSUE THREAD

**Issue by TakWolf** [RazrFalcon/ttf-parser#37]
https://github.com/RazrFalcon/ttf-parser/blob/master/src/lib.rs#L580

```
pub struct Face<'a> {
    ...
}
impl<'a> Face<'a> {
    pub fn from_slice(data: &'a [u8], index: u32) -> Result<Self, FaceParsingError> { 
    }
}
```
It seems Face need reference the bytes for a long time.
I can not understand of the lifetime here, why it is necessity?
Is font parse not one-time action?

For this reason, I can't simply define a struct attr like:
```
pub struct Renderer {
    font: Face,     // <---- error!!! must gave a lifetime
}

```
This puts a lot of restrictions on the code design.
But i really can't figure it out.

**Comment by RazrFalcon** [comment]
You should use [owned-ttf-parser](https://github.com/alexheretic/owned-ttf-parser) instead. 

>Is font parse not one-time action?

No. ttf-parser parses the font parts on demand. Parsing the whole font into the memory is absurd and no one is doing this.

The lifetime is required, since `Face` doesn't allocate anything (at least on heap). At all.

**Comment by RazrFalcon** [comment]
As the comment above mentioned - just use [owned-ttf-parser](https://github.com/alexheretic/owned-ttf-parser).

And yes, depending on your performance requirements you might be fine with re-parsing the `Face` on each access.
`Face::parse` doesn't actually parse the whole font, only some basic metadata.

**Comment by RazrFalcon** [comment]
Yes. `owned-ttf-parser` is just a wrapper for `ttf-parser`. See [docs](https://docs.rs/owned_ttf_parser/latest/owned_ttf_parser/).

**Comment by bennoinbeta** [comment]
> Yes. `owned-ttf-parser` is just a wrapper for `ttf-parser`. See [docs](https://docs.rs/owned_ttf_parser/latest/owned_ttf_parser/).

Thanks for the quick information. I'll explore both caching and not caching the Face to see what works best for my SVG text rendering project. Also, a big thanks for developing rustybuzz & ttf-parser – it looks like a great fit for my needs 👍🙏
