### ISSUE TITLE
Point direction request

### ISSUE THREAD

**Issue by mooman219** [RazrFalcon/ttf-parser#43]
I ran into this font which defines and uses glyphs in the `CFF` and `glyf` tables: https://github.com/emilk/egui/blob/master/egui/fonts/Comfortaa-Regular.ttf

My rasterizer needs to know the point winding before it can run `outline_glyph`. For TrueType, a counter clockwise contour will always define the outside edge of a filled area, and a clockwise contour will always define the inside edge of a filled area. This is reversed for OpenType fonts.

Is there a way to know if for a given `GlyphId`, the glyph is from an OpenType table or TrueType table?

**Comment by RazrFalcon** [comment]
I can add a `glyph_source` method which will return the `TableName` or a specific type. We have 7 glyph sources right now.

**Comment by RazrFalcon** [comment]
By the way, the font that you have linked doesn't have a CFF table.

**Comment by mooman219** [comment]
Apologies, I assumed it had a an OTF table like CFF in it because some of the points are defined in the wrong winding order. This may just be a malformed font.

I would appreciate the glyph_source method for where the glyph's outline is sourced from. This would remove some ambiguity.

**Comment by mooman219** [comment]
Some extra information on point ordering for TrueType fonts:

![image](https://user-images.githubusercontent.com/865769/96187395-c7631a00-0ef1-11eb-95c6-5e2cec9f8650.png)

Contours that need to be filled black must have a clockwise direction. If we want to make a white area inside an existing contour we must make the direction of the new contour counter clockwise. Contour direction is determined by seeing in which direction the point index values increase or decrease. Contour direction is from the smaller point index to the larger. The general rule is that the contour direction should be such that "black is on the right". Using the glyph "O" as an example, the outer contour should travel clockwise, and the inner contour counter clockwise.

For CFF based contours the direction is exactly the opposite, so contours that need to be filled black must have a counter clockwise direction.

**Comment by RazrFalcon** [comment]
1. Can I reproduce the issues with `Comfortaa-Regular.ttf`?
1. Can you post a link to the specification were this behavior is explained?
1. Emitting points in reverse is highly problematic, since we do not allocate, therefore we have to store points on stack first, which is quite limiting.
1. I will check what freetype does in this case.

**Comment by mooman219** [comment]
1. Yes
2. This font may just be out of spec, but [Apple notes the contour order restriction here](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM01/Chap1.html). It appears stb_truetype will flip the points.
3. Really only the individual calls in OutlineBuilder need to be reversed.
4. Okay

**Comment by RazrFalcon** [comment]
Very strange. FreeType produces the same outline, but the points order and values are very different. Looks like the problem no in mirroring, bit in the second contour points order. 

I will try to write a tool that will help me with debugging this issue tomorrow.

The most interesting part, is that if you export both outlines (ttf-parser one and ft2 one) to SVG, they will be filled equally, while having different points. Here: [issue-43-test.zip](https://github.com/RazrFalcon/ttf-parser/files/5393880/issue-43-test.zip)
This is probably the reason why I'm missed this.

**Comment by RazrFalcon** [comment]
So I've added points enumeration:

FreeType:

![ft](https://user-images.githubusercontent.com/725494/96302858-24e68c00-1002-11eb-8ae4-e5a7feddc993.png)

ttf-parser:

![ttfp](https://user-images.githubusercontent.com/725494/96302869-29ab4000-1002-11eb-82e1-c36231627519.png)

As you can see, the points order/direction is roughly the same. Looks like FreeType does some slight changes to the output (not rounding). I will have to run FreeType under debugger to figure it out.

**Comment by RazrFalcon** [comment]
So in the end, mirroring and direction are the same as in FreeType. Maybe the problem is somewhere else?

**Comment by mooman219** [comment]
Given this is a glyph from the `glyf` table, the outer outline should be counter clockwise for this character `b`. It may just be that FreeType is correcting it internally.

**Comment by RazrFalcon** [comment]
Here is 225 'b'. The directions is still correct.

FreeType:

![ft](https://user-images.githubusercontent.com/725494/96335037-f7d7bf00-107d-11eb-8bf3-2058fdd8e9ee.png)

ttf-parser:

![ttfp](https://user-images.githubusercontent.com/725494/96335042-fad2af80-107d-11eb-8d29-3c9d3e7dc45b.png)

>I don't think any solution here is elegant,

First, we have to prove that there are an actual bug.

**Comment by hasenbanck** [comment]
Just as an information. I just downloaded the version from the google fonts directory and this version doesn't seem to have this problem:
https://fonts.google.com/specimen/Comfortaa

So it might very well be that the TTF file in the above repository is just plain broken.

**Comment by RazrFalcon** [comment]
@hasenbanck Yes, that font version doesn't mirror `d` for `b`. But it doesn't seem like the old font itself have a bug. ttf-parser, freetype and harfbuzz are processing it correctly. Something is missing between `ttf-parser` and `fontdue`.

**Comment by mooman219** [comment]
@RazrFalcon Your images are upside down, and also both of your comments for 'b' and 'd' have different windings which illustrates the problem.

**Comment by RazrFalcon** [comment]
All I was able to find is [FT_Outline_Get_Orientation](https://freetype.org/freetype2/docs/reference/ft2-outline_processing.html#ft_outline_get_orientation), which indeed returns `FT_ORIENTATION_POSTSCRIPT` for `d` and `FT_ORIENTATION_TRUETYPE` for `b`. I will see how freetype implements it.

PS: And could you please tone down your demands. This is open source and not a commercial support line.

**Comment by mooman219** [comment]
> PS: And could you please tone down your demands. This is open source and not a commercial support line.

Apologies that the last comment came on too strong.  I worded the comment to more directly specify the issue in `ttf-parser` in response to "First, we have to prove that there are an actual bug", which felt like a dismissal that there was an issue in the first place.

**Comment by RazrFalcon** [comment]
Ok. My point was that there is no bug, if all other libraries are doing the same. Which is still true. 
I consider this a feature, not a bug. Because the current code is correct. You just want information, which is unnecessary in many cases. Aka optional.

**Comment by RazrFalcon** [comment]
So `FT_Outline_Get_Orientation` is [very simple](https://github.com/freetype/freetype2/blob/f9f6adb625c48ef15b5d61a3ac1709a068ea95a3/src/base/ftoutln.c#L1039). It tires to fill a path and accumulates the final area. That it. So I guess you can implement this on your side. Since in case of `ttf-parser` we would have to outline the glyph twice or track the area.

Once again, I don't see a bug here. It's a tricky feature with no clear solution. And as far a I can tell, transformations has nothing to with this. You can make such malformed font even without transformations.

Also, looks like it's not `glyf` specific. CFF also affected.

**Comment by mooman219** [comment]
Thank you for the extra information and context on freetype's solution. I agree this is a malformed font and not a failure on ttf-parser's side. Given this, I agree that a feature request for exposing the transforms doesn't fix the problem that fonts can just be malformed in a different way to produce the same bad result.

Would the feature request for the glyph source still be reasonable to add in `ttf-parser`? Right now I'm guessing the source based on the tables present in the font.

**Comment by RazrFalcon** [comment]
Sure, I will add such method.

**Comment by RazrFalcon** [comment]
>Right now I'm guessing the source based on the tables present in the font.

I think that this is the right way to do this. I've updated the docs. They mention parsing order now.

The problem with `glyph_source` method is that it's too vague. We have glyph outlining method and raster glyph extraction method. And outlining in case of `glyf` and variable fonts becomes even more confusing.

Basically, the current implementation is `gvar`+`glyf` -> `glyf` -> `cff` -> `cff2`. No fallback.
