### ISSUE TITLE
Port GPOS/GSUB from rustybuzz

### ISSUE THREAD

**Issue by jbowtie** [RazrFalcon/ttf-parser#44]
These three tables are key to modern fonts, especially for non-latin scripts.

`rustybuzz` already parses these tables to do glyph substitution and positioning, so the parsing code simply needs to be refactored for use in this library.

(If there's some reason keep the parsing of said tables in `rustybuzz`, it should be documented in the README)

**Comment by RazrFalcon** [comment]
GDEF already present. GPOS/GSUB are very low level and it's hard to provide a decent API for them. Especially in a non-allocating way.

Why do you need those tables?

**Comment by jbowtie** [comment]
In my case I want to enumerate the ligatures and alternates stored in the GSUB table. I also need to verify script support in some cases.

The README already mentions why certain tables are not supported; if you think it's not worth porting a quick note in the README would convince me it's worth rolling my own code for my use case rather than making a drive-by contribution.

**Comment by RazrFalcon** [comment]
Ok, seems reasonable. I will see if I can come up with a nice API. 

The original goal of this library was to hide the internals as much as possible, but looks like it not really possible.

**Comment by jbowtie** [comment]
Well, if someone is using the `ttf-parser` directly they're either writing a shaping algorithm or doing advanced text things like allowing people to select alternate forms.

If you even recognize the table names you're far lower-level than most programmers want to go anyway. 😆  I only got into font processing because I wanted to generate a PDF in my language of choice and fell down the Unicode rabbit hole.

**Comment by RazrFalcon** [comment]
Sure. But something like `outline_glyph` hides like 4000 LOC.

Implementing some tables on the rustybuzz side was just simpler for the initial release, since we can ignore a lot of things.

**Comment by RazrFalcon** [comment]
Well, it took way longer that expected. The API is quite low-level, compared to other ttf-parser API. And I had to rewrite rustybuzz implementation almost from scratch. But in the end, we have almost complete GDEF/GSUB/GPOS support.

**Comment by jbowtie** [comment]
Unexpected but much appreciated!  I'll have a closer look over the next couple of weeks but at first glance the API looks very clean.
