### ISSUE TITLE
Outline utilities

### ISSUE THREAD

**Issue by chrsan** [RazrFalcon/ttf-parser#46]
Hi!

I'm playing around with replacing FreeType with tff-parser in one of my projects.
I've made a couple of changes to be able to embolden and slant an outline.
The embolden algorithm is ported directly from the FreeType sources. To change
as little as possible of the original source I added a new method (that does nothing by default)
on the `OutlineBuilder` trait. The rest of the functionality lives in it's own module.

You can check my commit in this branch if interested:

https://github.com/chrsan/ttf-parser/tree/outline_utils

**Comment by RazrFalcon** [comment]
Thanks. I do not plan adding any post-processing features. ttf-parser will remain, well, a parser.

**Comment by jrmuizel** [comment]
@chrsan can you publish the outline utilities as a separate crate that depends on `ttf-parser`?

**Comment by chrsan** [comment]
@jrmuizel Not right now since the outline utilities depends on crate private things in `ttf-parser`. I'll try to see if I can understand the embolden algorithm in FreeType a bit better, but as is it's operating on the _raw_ glyph points. And I can't access those outside of `ttf-parser`. At least not for TrueType fonts.
