### ISSUE TITLE
Propperly use usWin* instead of hhea for ascend/descend when USE_TYPO_METRICS not set

### ISSUE THREAD

**Issue by JAicewizard** [RazrFalcon/ttf-parser#53]
According to the microsoft specification `usWin*` should be used  for getting the ascend/descend if the USE_TYPO_METRICS bit is not set.
I am specifically hitting this with some fonts from fontlab where the USE_TYPO_METRICS bit is not set and the `hhea` table is practically empty.

Source for specification:
https://docs.microsoft.com/en-us/typography/opentype/spec/os2#stypoascender

**Comment by RazrFalcon** [comment]
I'm not sure I've understood you. Are you saying that when `USE_TYPO_METRICS` is not set and `OS/2` is present we should use `OS/2::usWinAscent` instead of `hhea::ascender`?

**Comment by JAicewizard** [comment]
Yes, that's how I read the specification and apparently also how the font I am currently dealing with wants it to be read.

**Comment by RazrFalcon** [comment]
Could you open your font in [ttf-explorer](https://github.com/RazrFalcon/ttf-explorer) and check what values are you actually having. I've tested a couple of fonts in most of them `OS/2::usWinAscent` and `hhea::ascender` are identical (usWin is inverted actually). I just want to be sure that the actual issue.

**Comment by JAicewizard** [comment]
I go these using fontdump, I will see if I can install ttf-explorer in a minute:
```
...
'hhea' Table - Horizontal Header
--------------------------
         'hhea' version:         1.0
         yAscender:              0  //<<<<<<<<<<<<<<<<< not set
         yDescender:             0  //<<<<<<<<<<<<<<<<< not set
         yLineGap:               0
         advanceWidthMax:        1000
         minLeftSideBearing:     0
         minRightSideBearing:    0
         xMaxExtent:             668
         caretSlopeRise:         1
         caretSlopeRun:          0
         reserved0:              0
         reserved1:              0
         reserved2:              0
         reserved3:              0
         reserved4:              0
         metricDataFormat:       0
         numberOfHMetrics:       5
...
'OS/2' Table - OS/2 and Windows Metrics
---------------------------------------
         'OS/2' version:         4
... (still OS/2)
         fsSelection:            0x0040          'Regular ' //<<<<<<<<<<<<<<<<< bit 7 not set
         usFirstCharIndex:       0x0000
         usLastCharIndex:        0x004b
         sTypoAscender:          0 //<<<<<<<<<<<<<<< not set
         sTypoDescender:         0//<<<<<<<<<<<<<<< not set
         sTypoLineGap:           0
         usWinAscent:            250 //<<<<<<<<<<<<<<< set
         usWinDescent:           250 //<<<<<<<<<<<<<<< set
...```

**Comment by RazrFalcon** [comment]
That's all I wanted to know. Yes, this is a weird/unusual font. I will take a look at this on the weekends.

**Comment by JAicewizard** [comment]
Thanks for looking into this.
I think that in case you dont want to switch over, it might make sense to at least check if hhea is 0, and if so use usWin for weird cases like this.
For reference this font was made with FontLab, I dont personally have a license so I cant test out what settings make this happen.
