### ISSUE TITLE
How to get maximum character width?

### ISSUE THREAD

**Issue by dabreegster** [RazrFalcon/ttf-parser#56]
I'm trying to render a text entry box that allows for up to 30 characters to be entered. To calculate its width, I need to know the max possible width of a 30-character string. Assuming nothing funny happens with spacing between letters, I _think_ I can just multiply 30 by the max width of any character in that font.

I found [global_bounding_box](https://docs.rs/ttf-parser/0.12.0/ttf_parser/struct.Face.html#method.global_bounding_box), and so I'm trying this:

```
let font_id = ...;
let font_size = 21;
fontdb.with_face_data(font_id, |data, face_index| {
        let font = ttf_parser::Face::from_slice(data, face_index).unwrap();
        let scale = (font_size as f64) / (font.units_per_em().unwrap() as f64);
        scale * font.global_bounding_box().width() as f64
})
```

For the Overpass regular font, I get 30.4 from this, which seems visually to be too wide for most of the alphanumeric characters I'm trying out. Is there maybe an outlier character that's especially wide, or is this calculation incorrect? I'm not sure what units `global_bounding_box` returns, nor if my understanding of `units_per_em` is correct.

Thanks!

**Comment by RazrFalcon** [comment]
`global_bounding_box` returns a rectangle that is guaranteed to feet any glyph in the font. But it's not a tight box, afaik. And it doesn't even have to be correct. It just a random value stored in the font. It's not calculated or anything.

Calculating a width of N characters for non-monospaced font in general doesn't make any sense. In most cases it would be too wide.

There are a lot of values you might be interested in [hhea](https://docs.microsoft.com/en-us/typography/opentype/spec/hhea) table, but ttf-parser doesn't export most of them. This is an easy fix.

> units_per_em

This is just an internal font scale. It's used to convert between font units and application units (like `pt`).

**Comment by dabreegster** [comment]
> Calculating a width of N characters for non-monospaced font in general doesn't make any sense.

I'm guessing most text boxes with a character limit are manually tuned, then, and support horizontal scrolling. I'll probably take this route, then. Thanks for confirming!

> There are a lot of values you might be interested in hhea table

I might experiment with `ttf-explorer` and learn about these, but no need to expose here.
