### ISSUE TITLE
Symbola.ttf invalid glyph bounds

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#57]
This font has glyph(s) that produce return invalid bounding boxes, e.g. with `y_min == y_max`. I'd expect these to return `None` when calling `outline_glyph`.

Presumably this font is dodgy. Should _ttf-parser_ handle this or should I downstream?

### Reproduce
```rust
// [dependencies]
// ttf-parser = "0.12"

/// https://github.com/gearit/ttf-symbola/raw/master/Symbola.ttf
const FONT: &[u8] = include_bytes!("../Symbola.ttf");

fn main() {
    let face = ttf_parser::Face::from_slice(FONT, 0).unwrap();
    let gid = ttf_parser::GlyphId(893);

    let bounds = face.outline_glyph(gid, &mut OutlinePrinter);
    eprintln!("outline_glyph({:?}, _) = {:?}", gid, bounds);
    if let Some(b) = bounds {
        assert!(b.x_min < b.x_max && b.y_min < b.y_max);
    }
}

struct OutlinePrinter;

impl ttf_parser::OutlineBuilder for OutlinePrinter {
    fn move_to(&mut self, x: f32, y: f32) {
        eprintln!("outline-move_to({}, {})", x, y);
    }
    fn line_to(&mut self, x: f32, y: f32) {
        eprintln!("outline-line_to({}, {})", x, y);
    }
    fn quad_to(&mut self, x1: f32, y1: f32, x: f32, y: f32) {
        eprintln!("outline-quad_to({}, {}, {}, {})", x1, y1, x, y);
    }
    fn curve_to(&mut self, x1: f32, y1: f32, x2: f32, y2: f32, x: f32, y: f32) {
        eprintln!(
            "outline-curve_to({}, {}, {}, {}, {}, {})",
            x1, y1, x2, y2, x, y
        );
    }
    fn close(&mut self) {
        eprintln!("outline-close");
    }
}
```

```
outline-move_to(0, 1606)
outline-line_to(0, 1606)
outline-close
outline-move_to(2048, 1606)
outline-line_to(2048, 1606)
outline-close
outline_glyph(GlyphId(893), _) = Some(Rect { x_min: 0, y_min: 1606, x_max: 2048, y_max: 1606 })
thread 'main' panicked at 'assertion failed: b.x_min < b.x_max && b.y_min < b.y_max', src/main.rs:14:9
```

ab-glyph issue: https://github.com/alexheretic/ab-glyph/issues/32

**Comment by RazrFalcon** [comment]
I honestly have no idea how it should be handled. TrueType spec doesn't seems to specify it.
I will have to check other implementations to see what they do.

**Comment by mooman219** [comment]
> I will have to check other implementations to see what they do.

If it's worth anything,

Fontdue computes bounds on the fly. Chromium also computes bounds on the fly / has specific handling for some specific dodgy but popular fonts. Some in the wild fonts also use i16::MAX / i16::MIN instead of 0 sometimes for bounds. I have a growing hall of shame for these degenerate fonts.

**Comment by RazrFalcon** [comment]
@mooman219 Yes, ideally, the embedded bbox should match calculated one. But I'm not sure what to do when they are different. What if the font's author wanted the bbox to be different.

ttf-parser already have an optional bbox calculation, so this is will be a trivial fix. I just want to make sure we're doing the right thing (and there are no right ways in the fonts world).

**Comment by RazrFalcon** [comment]
@alexheretic 

Here is freetype output:

```
xMin 0
yMin -1606
xMax 2048
yMax -1606

Segments:
- MoveTo(x=2048, y=-1606)
```

And here is harfbuzz output:

```
x_bearing 0
y_bearing 1606
width 2048
height 0

Segments:
- MoveTo(x=0, y=0)
```

So I guess that ttf-parser output is correct, I just have to document such behaviour. And you should handle it on your side.

**Comment by alexheretic** [comment]
Ok will do, thanks for investigating.

**Comment by RazrFalcon** [comment]
Funnily enough, I've just hit exactly the same bug: https://github.com/RazrFalcon/ttf-parser/commit/856de6e2967fe91eb32f9a9c4390117d89195998

Zero-sizes glyphs are just fine, sadly.
