### ISSUE TITLE
Fails to outline 'i' in Carlito font

### ISSUE THREAD

**Issue by dhardy** [RazrFalcon/ttf-parser#59]
I've been wondering why 'i' does not get rendered with this font (most glyphs do render). Is this hitting an unsupported feature?

Code: https://gist.github.com/dhardy/60ef7de0e291e54ef7b4e2f8b95e1819  
Font: `/usr/share/fonts/google-carlito-fonts/Carlito-Regular.ttf`

Output:
```
ttf-parser index: 98
ttf-parser bounding box: Rect { x_min: 110, y_min: 0, x_max: 357, y_max: 1409 }
ttf-parser failed to outline glyph
fontdue index: 98
fontdue metrics: Metrics { xmin: 0, ymin: 0, width: 0, height: 0, advance_width: 9.1796875, advance_height: 0.0, bounds: OutlineBounds { xmin: 0.0, ymin: 0.0, width: 0.0, height: 0.0 } }
```

**Comment by RazrFalcon** [comment]
Can you send the font file itself or at least its hash?

**Comment by dhardy** [comment]
Sorry, here's the sum:
```
$ sha256sum /usr/share/fonts/google-carlito-fonts/Carlito-Regular.ttf
b4ff23ba370cc95a3c349336b73f9c28514a1371210f89832efc85c4b1ea7131  /usr/share/fonts/google-carlito-fonts/Carlito-Regular.ttf
```
Should be this package: https://fedora.pkgs.org/34/fedora-x86_64/google-carlito-fonts-1.103-0.16.20130920.fc34.noarch.rpm.html

**Comment by mooman219** [comment]
![image](https://user-images.githubusercontent.com/865769/121431797-b8bced80-c92e-11eb-94b3-f5811a0cd2a9.png)

That letter `i` is a composite of 3 glyphs. The stem, the dot, and this third glyph in the image. Seems degenerate.

![image](https://user-images.githubusercontent.com/865769/121431643-84493180-c92e-11eb-818f-fa7302983fca.png)
