### ISSUE TITLE
Define a rustfmt.toml

### ISSUE THREAD

**Issue by mooman219** [RazrFalcon/ttf-parser#60]
https://rust-lang.github.io/rustfmt/

I started writing a PR to add iterators for the 3 supported Kerning tables, but trashed the file formatting on save to my defaults. Do you mind adding a `rustfmt.toml` to your root with the styling you prefer?

**Comment by RazrFalcon** [comment]
I don't like autoformatting tools. I suggest disabling autofomatting in your editor.

**Comment by mooman219** [comment]
That's reasonable, I'll do that. I wasn't sure if you had a preference.

**Comment by RazrFalcon** [comment]
Thanks for understanding.
