### ISSUE TITLE
Support platform id 7 PLATFORM_ADOBE 

### ISSUE THREAD

**Issue by naivefeeling** [RazrFalcon/ttf-parser#65]
https://www.freetype.org/freetype2/docs/reference/ft2-truetype_tables.html#tt_platform_xxx

**Comment by RazrFalcon** [comment]
So do you need just a flag? Or do you need something else? Like accessing the encoding table itself.

**Comment by RazrFalcon** [comment]
This is not as easy as I've thought. We first have to support #33.

**Comment by RazrFalcon** [comment]
I have added CFF Encoding support. I still have no idea how `TT_PLATFORM_ADOBE` works, but you can use `cff::Table::glyph_index` to convert byte/codepoint to glyph ID now.
