### ISSUE TITLE
Are there plans to support COLR/CPAL tables?

### ISSUE THREAD

**Issue by yisibl** [RazrFalcon/ttf-parser#69]
- COLRv0: https://docs.microsoft.com/en-us/typography/opentype/spec/colr
- COLRv1: https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/colr

COLR format fonts are part of the OpenType specification. It is the perfect companion for emoji and font icons in usage scenarios. This has become so popular that all major browsers support COLRv0.

![image](https://user-images.githubusercontent.com/2784308/138440311-82edf9b6-8406-438b-a272-e49c74558f8b.png)

And Chrome will soon [ship COLRv1](https://groups.google.com/a/chromium.org/g/blink-dev/c/kDfj3rcA6sc), which will bring many new features such as gradients, transforms and compositing.

2023-09-21

![image](https://github.com/RazrFalcon/ttf-parser/assets/2784308/ee4fd556-aff3-4a2e-9ea7-122dce76e0eb)

**Comment by RazrFalcon** [comment]
Current progress: #133
