### ISSUE TITLE
v0.13 font CooperHewitt vmetrics regression

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#81]
I've had reports of issues with font _CooperHewitt-Book.otf_ (https://uh8yh30l48rpize52xh0q1o6i-wpengine.netdna-ssl.com/wp-content/uploads/fonts/CooperHewitt-OTF-public.zip) using _ttf-parser_ 0.13.

0.13 does calculate the ascender/descender values differently from 0.12.
```
CooperHewitt-Book.otf
- v0.12 face.ascender() = 1000
- v0.12 face.descender() = -300

- v0.13 face.ascender() = 750
- v0.13 face.descender() = -250
```

This is causing problems rendering the higher glyphs. Running the font through the **font2svg** example it does also seem to suggest something is wrong with the values returned.

![](https://user-images.githubusercontent.com/2331607/146204245-7a8dd874-6cb7-460c-a79a-3f9ce6f48a7f.png)

Downstream: https://github.com/alexheretic/ab-glyph/issues/50

**Comment by RazrFalcon** [comment]
The new version is correct. At least it produces the same values as FreeType. As was mentioned before, this is [completely undefined](https://github.com/freetype/freetype/blob/49270c17011491227ec7bd3fb73ede4f674aa065/src/sfnt/sfobjs.c#L1279).

**Comment by RazrFalcon** [comment]
Seems like you have to force Windows metrics somehow. But this cannot be done automatically, afaik. Not sure what FT does in this case.

**Comment by alexheretic** [comment]
I'm not sure it's a v-centering thing, the height just looks insufficient to contain the taller glyphs. Here's an the font2svg for the _Medium_ weight

![cooper-hewitt-medium-font2svg](https://user-images.githubusercontent.com/2331607/146209821-ed82b502-a25d-4b6a-975f-88a10599298f.png)

**Comment by RazrFalcon** [comment]
FreeType returns exactly the same values. Here is testing-tools/font-view output:
![Screen Shot 2021-12-15 at 16 57 35](https://user-images.githubusercontent.com/725494/146209990-c7924160-3588-4176-9359-df86b028ff03.png)


So I guess it should be handled on your side, but I have no idea how.

**Comment by alexheretic** [comment]
Ok thanks for investigating. 

So it's not the case that ascender/descender height should always contain the glyphs?

**Comment by RazrFalcon** [comment]
Moreover, line height is technically infinite, see q̸̥̹̌́̓̐̾͐̏̎̔̀͌̽͊̿͌̊͠w̵̨̧̡̡̮̩͓̮͍̪̤̙̘̯̝͕̖̗̱͇͚̳̤̯̬̥̔͛͆́̑̄̐̓̀̊́̽̆̀̅̔͊͘̕̚̕͘͜͠͠͠ͅͅe̵̛̜̟͇͓̗͓͉̫̮̣̮̙̬̬̩̪̙̹̤̬̬͎̩̎̐̇̆̎̍̂͌́͋̀̏̔̿̿̓́́̈́̌̔̉͋̅̍̋́̓̿̆̑̓̐͊͂̈́̿̏̚͠͝͠q̷̧̨̨̧̛̺̪͎̭͉͔͈͕͚̼͔͇̯͖͙̳̟͙̠͇̫͕͔̱̦̰̣͓͇͔͓̪̹̥̙͑̍͊̓̓͋͂̊́̿͑͊̔̌̈́̌͒̋̔̽͘͝͝͝͠ͅͅͅͅw̷̛̭̫̲͓͎̏̅̀̇͑́͗̑́̚͝͠͝ę̶̙̏̐̊́͘͘

**Comment by alexheretic** [comment]
The rendering is fine, I think, the pixel bbox is still correct. I already using line_gap, but it isn't currently used on the first line, only for gaps between lines. Perhaps I should include it in all lines. Anyway thanks for the explanations!
