### ISSUE TITLE
A bug with "Roboto Black" font's kerning table

### ISSUE THREAD

**Issue by Eliah-Lakhin** [RazrFalcon/ttf-parser#84]
Font file source: https://fonts.google.com/specimen/Roboto?preview.text=To&preview.text_type=custom

The file from the fileset is `Roboto-Black.ttf`.

Google font preview clearly shows there is a kerning between `T` and `o` chars. https://fontdrop.info/ confirms there is a `kern` table. However `Face::tables(..).kern` is `None` for this font file.

**Comment by RazrFalcon** [comment]
There are no `kern` tables in those fonts. You can check it using [ttf-explorer](https://github.com/RazrFalcon/ttf-explorer).

**Comment by RazrFalcon** [comment]
The "kerning" is probably stored in `GPOS`.

**Comment by Eliah-Lakhin** [comment]
Yes, it's all in the `GPOS` table, you are right. Thank you for your help and for the great library! I managed to fetch this data.
