### ISSUE TITLE
Some fonts don't return a name because of encoding

### ISSUE THREAD

**Issue by MoAlyousef** [RazrFalcon/ttf-parser#85]
Hello
Thanks for this library. I noticed that some fonts, namely [Octicons.ttf](https://github.com/oblador/react-native-vector-icons/blob/master/Fonts/Octicons.ttf) in addition to [font awesome](https://fontawesome.com/download) don't return a name, or more specifically return an "unsupported encoding". 

I've tried to modify ttf-parser to allow for lossy utf8 encoding and it seems to work:
```rust
// src/tables/name.rs
    pub fn to_string(&self) -> Option<String> {
        if self.is_unicode() {
            self.name_from_utf16_be()
        } else {
            use std::string::ToString;
            Some(String::from_utf8_lossy(self.name).to_string())
        }
    }
```
Which appears to work on both Linux (wsl) and windows.

**Comment by RazrFalcon** [comment]
What code do you use to get a name? This one works just fine:

```rust
    let family_name = face.names().into_iter()
        .find(|name| name.name_id == ttf_parser::name_id::FULL_NAME && name.is_unicode())
        .and_then(|name| name.to_string());

    let post_script_name = face.names().into_iter()
        .find(|name| name.name_id == ttf_parser::name_id::POST_SCRIPT_NAME && name.is_unicode())
        .and_then(|name| name.to_string());
```

PS: The font-info example should be corrected...

**Comment by MoAlyousef** [comment]
Ah. Yeah I used the code from the font-info example. I'll close this issue.
Thanks for the prompt response.
