### ISSUE TITLE
Are there any plans on supporting the MATH table?

### ISSUE THREAD

**Issue by ruifengx** [RazrFalcon/ttf-parser#86]
https://docs.microsoft.com/en-us/typography/opentype/spec/math

P.S. The types `Face` and `RawFaceTables` are not extensible in current design. Is it possible to expose the raw tables not recognised during `Face::from_slice`? Then it might be possible to utilise the API exposed in the `parser` module to do some custom parsing in downstream crates (and perhaps PR back here after thorough testing).

**Comment by RazrFalcon** [comment]
Technically, all tables are planned, but priority is varied. 

If you want to parse this table yourself - simply use `Face::table_data`.

**Comment by ruifengx** [comment]
Ah, thanks! How could I have missed that function!
