### ISSUE TITLE
Fails to Parse Adobe Source Han Variable Font OTFs

### ISSUE THREAD

**Issue by lunabunn** [RazrFalcon/ttf-parser#88]
ttf-parser seems to be unable to recognize glyphs in Adobe Source VF OTFs. While I didn't test every combination, the problem seems to be present across both [Source Han Sans](https://github.com/adobe-fonts/source-han-sans/tree/release) and [Source Han Serif](https://github.com/adobe-fonts/source-han-serif/tree/release) across all language varieties.

I would check what tables the font is using and compare it with the support table in the README for some insight, but FontForge, opentype.js, and Typr.js all also failed to parse the fonts, so I can only assume the fonts are using some very obscure features 😓 

For comparison/reference, the corresponding TTF fonts are parsed correctly.

**Comment by mooman219** [comment]
For reference, Windows seems to have no issues parsing and installing the fonts. +1 on assuming the fonts are using some very obscure features, or have a malformed table.

**Comment by RazrFalcon** [comment]
Well, it does state that:

>WARNING: Currently Windows 10 and Windows 11 do not support CFF2 variable fonts. Please use the TTF variable instead.

But we do support CFF2. And font2svg example produces the correct output. How exactly are you using ttf-parser? As a library or indirectly?

I've tested `SourceHanSans-VF/Variable/OTF/SourceHanSans-VF.otf` and `SourceHanSans-VF/Variable/OTF/Subset/SourceHanSansJP-VF.otf`
