### ISSUE TITLE
update dependencies?

### ISSUE THREAD

**Issue by dkg** [RazrFalcon/ttf-parser#89]
The following three crates that ttf-parser depends or dev-depends on have more recent versions available upstream:

crate | ttf-parser depends on version | current upstream version
----|----|----
base64 | 0.12 | 0.13
pico-args | 0.3.1 | 0.4.2
svgtypes | 0.5 | 0.8.0

i think pico-args and svgtypes are both maintained by you, @RazrFalcon !  and [base64 changes in 0.13.0](https://github.com/marshallpierce/rust-base64/blob/master/RELEASE-NOTES.md#0130) shouldn't be too complicated to adapt to.

Can you update  ttf-parser to use the newer versions of these crates (at least to the next semver API change)?  I want to bring the latest version of both ttf-parser and svgtypes into debian unstable, and these older dependencies make it difficult.

**Comment by RazrFalcon** [comment]
Done.
