### ISSUE TITLE
Font with unusual format 4 cmap subtable where terminating FFFF endCode has idRangeOffset of FFFF reports FFFF as a codepoint from `Subtable4::codepoints`

### ISSUE THREAD

**Issue by the6p4c** [RazrFalcon/ttf-parser#90]
I'm not 100% sure if this should be considered a bug with `ttf-parser`, or with upstream code which uses the `codepoints` function to iterate through the supported codepoints and then retrieve their glyph indices. However:

Within the [Monofur](https://www.dafont.com/monofur.font) font, a format 4 cmap subtable has a standard terminating `FFFF` `endCode`, defining a `FFFF` to `FFFF` segment. The segment has `idRangeOffset` of `FFFF` - clearly out of range for the `glyphIdArray` that follows - and a `0001` `idDelta` (at least that's normal).

Calling `Subtable4::codepoints` reports the `0xffff` codepoint from this segment to callers. However, then calling `Subtable4::glyph_index` with `0xffff` yields `GlyphId(10496)` (can't be correct - the `idRangeOffset` points outside of the table, and that glyph ID is too large for the font). In code that does this (namely [fontdue](https://github.com/mooman219/fontdue/blob/35770aaa91247f338f71891e977a87cfce7b748d/src/font.rs#L257-L278)) this causes a panic ("Attempted to map a codepoint out of bounds.") due to the glyph ID 10496 not existing.

I could see reason to make `Subtable4::codepoints` never report `0xffff` as a codepoint, considering it is defined to not be a character, but also reason to say that calling code like `fontdue` shouldn't request the glyph index for `0xffff`. I wouldn't want to reject the table as invalid - the font works! It's just this one funky entry at the end.

**Comment by the6p4c** [comment]
Interesting to note that [freetype acknowledges many fonts get the last segment wrong](https://github.com/freetype/freetype/blob/d0cfb4e1b227ce088181627b07619ee08fe6a073/src/sfnt/ttcmap.c#L684-L687).

**Comment by RazrFalcon** [comment]
It's a good question. A valid Subtable4 would always have `0xffff` at the end and since this is a special value we should probably ignore it. But `glyph_index` should not return an invalid value anyway.

I've decided to exclude `0xffff` from `Subtable4::codepoints` and fixed `glyph_index` too.
