### ISSUE TITLE
Replacement for `FaceTables::from_table_provider`

### ISSUE THREAD

**Issue by rramphal** [RazrFalcon/ttf-parser#92]
Last year, I was using v0.12.3 which provided the `FaceTables::from_table_provider` function. When I tried to upgrade to the latest v0.15.0, I found that function was no longer there. Has it been completely removed, or has it been moved/renamed? Would someone be able to suggest an alternative approach?

Thank you!

**Comment by RazrFalcon** [comment]
You should use [RawFaceTables](https://docs.rs/ttf-parser/latest/ttf_parser/struct.RawFaceTables.html#) now.

**Comment by rramphal** [comment]
Thank you for pointing me in the right direction!

This might be an ignorant question, but currently I'm using `font-kit` to get a list of font handles, load them, and extract their `head`, `hhea`, `maxp`, and `cmap` tables. Once I have those, I am creating a `Face` from `RawFaceTables`, and then I call `face.tables().cmap` to get to the subtables. Once I have the subtables, I iterate over them to get codepoints. Is there a quicker way to get the codepoints? Once I have the `cmap` table from `font-kit`, can I get the codepoints directly without going through a `Face`; or are the other `head`, `hhea`, and `maxp` tables necessary to correctly parse a `cmap` table?

**Comment by RazrFalcon** [comment]
Yes, you can use https://docs.rs/ttf-parser/latest/ttf_parser/cmap/struct.Table.html#method.parse

**Comment by rramphal** [comment]
Of course — thank you for your help!
