### ISSUE TITLE
curve control points should not extend bboxes

### ISSUE THREAD

**Issue by mlwilkerson** [RazrFalcon/ttf-parser#95]
**Expected:**
The glyph below should have a bbox  y_max of 439.

More precisely: 438.90, which would round up to 438.90906.

Anyway, it's greater than the y=438 on-curve point at the start of the contour.

**Actual**
The bbox y_max is 548.

**Analysis**

This appears to be the result of expanding the bbox

I have a glyph that looks like this:
![multi-rel-smooth-quadratic-expected](https://user-images.githubusercontent.com/11575183/166094944-5d8ebd79-4797-4a3a-b2cf-d618d4a45942.png)

It's made from an SVG that looks like this (the expected/actual y_max values above are based on the TTF coordinate grid, where y=448 would be the top of "view box", equivalent to y=0 on this SVG coordinate grid):

```svg
<svg  xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
  <path d="M10 10q 30 290 180 90t 20 40 40 60 60 80z"/>
</svg>
```

This is one of my test cases in another project. The test case exercises multiple Smooth Quadratic Curve with relative parameters, following a quadratic curve.

Here's a view of the resulting TrueType glyph in the FontForge UI:

<img width="574" alt="image" src="https://user-images.githubusercontent.com/11575183/166095076-a203f02a-6c26-47fa-9d32-b8b23ac96bdc.png">

The red arrow shows that the control point for a quadratic curve lands way outside the glyph's "view box" (red arrow), while the rendered curve remains inside the glyph's box (green arrow).

When computing the bbox of the glyph outline, I think the control point should not be used to expand the bbox. The control point is not within the bounding box, is it?

But currently, the code does extend the glyph's bbox with that quadratic curve control point:
https://github.com/RazrFalcon/ttf-parser/blob/396e9fcf678cf2b67c94cab27505f4d04ccb6d6c/src/tables/glyf.rs#L68

As a result, the y_max for the bbox is 548--it's been extended way out there to include that (off-curve) control point.

It does the same in the cubic curve handling for the CFF table:
https://github.com/RazrFalcon/ttf-parser/blob/master/src/tables/cff/mod.rs#L61-L62

Isn't it the case that we should only expand the bbox by a point that's actually _on_ the curve?

In these cases, it seems to require that we compute the extrema of the curve, such as those pointed at by the green arrow above. Those points would be neither the control point, nor the end points of the quadratic curve, so they will not be provided to the `quad_to()` function. They'd have to be _computed_, like these [quadratic](https://github.com/linebender/kurbo/blob/d0b956b47f219ba2303b4e2f2d904ea7b946e783/src/quadbez.rs#L343) and [cubic](https://github.com/linebender/kurbo/blob/d0b956b47f219ba2303b4e2f2d904ea7b946e783/src/cubicbez.rs#L511) bezier extrema calculations in the kurbo crate, wouldn't they?

**Comment by mlwilkerson** [comment]
The linked PR #96 includes a test case that reproduces the issue.

**Comment by RazrFalcon** [comment]
>When computing the bbox of the glyph outline, I think the control point should not be used to expand the bbox. The control point is not within the bounding box, is it?

That's a good question. I don't know. I don't think this is documented anywhere. We have to simply check what other implementations do. And afaik, at least [stb_truetype](https://github.com/nothings/stb/blob/af1a5bc352164740c1cc1354942b1c6b72eacb8a/stb_truetype.h#L1923..L1926), freetype and [harfbuzz](https://github.com/harfbuzz/harfbuzz/blob/9909e3326806f0ad1405648c16296cd42dff39fc/src/hb-ot-cff1-table.cc#L357..L359) do the same.

Also, calculating the real/tight bbox would be extremely expensive.

**Comment by khaledhosny** [comment]
From https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#glyph-headers:

> Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax). These values are obtained directly from the point coordinate data for the glyph, comparing all on-curve and off-curve points. Phantom points computed by the rasterizer are not relevant. Note that the bounding box defined by control points is guaranteed to contain the outline, but might not be tight to the outline.

**Comment by RazrFalcon** [comment]
@khaledhosny Thanks!

**Comment by mlwilkerson** [comment]
Wow, it's right there in the spec! Thanks, @khaledhosny. It's been too long since I read that section.

Now you that you point it out, it makes sense to me that at this low level, the bbox would be defined so loosely, for the sake of efficiency. But at some point, the price has to be paid to lay it out correctly, doesn't it?

Where I encountered the problem was when trying to rasterize it. I was using `ab-glyph` which depends on this crate to rasterize it, and then trying to get it positioned correctly on the 512x512 space that I know is the original viewBox. My goal is to compare the rendered SVG to the rendered font glyph.

So it seems that in order to lay it out correctly, that tighter bbox must be calculated _eventually_, so you're not positioning the rendered glyph with respect to some control point that's way outside the viewBox.

I recognize that this is no longer an issue with this crate, so I'll close this issue. But if you know of any more tips to point me in the direction for solving my problem, I'd appreciate it.

**Comment by RazrFalcon** [comment]
Well, you can calculate a tight bbox quite easily. I wrote this crate for [resvg](https://github.com/RazrFalcon/resvg) and [here](https://github.com/RazrFalcon/resvg/blob/5e8c634457a70f9ac2656dc59e40da841a8fbe9b/usvg/src/pathdata.rs#L335) is how it calculates the bbox (you would probably have to add the quad curve case).
Since it's quite expensive and requires a third-party dependency, it will not be part of ttf-parser.

I'm not sure about the glyph positioning itself. I haven't needed this before. In resvg, [rustybuzz](https://github.com/RazrFalcon/rustybuzz) (aka harfbuzz) positions glyphs for me. I just outline them and place where needed. The "real" bounds doesn't really matter for me.

Overall, ttf-parser is trying to be a good parser abstraction. It doesn't really do any post-processing (like let's say freetype). So any additional features should be implemented separately. Like [this](https://github.com/chrsan/ttf-utils).

**Comment by mlwilkerson** [comment]
I think I had an aha! moment and solved my problem well enough for now. This conversation was a key ingredient for shifting my perspective to see the solution, so thank you!

I do have tight bbox calculation implementation in my code, which I could use--if I had the absolute coordinate points of the original bezier curves as inputs. And that was my first guess: if ttf-parser and ab-glyph won't give me horizontal/vertical metrics based on the tight bbox, then I'd compute the tight bbox myself. But ab-glyph also doesn't seem to provide those points of the bezier curve that I would need in order to compute the tight bbox. This was another clue that I was still maybe trying to fit a square peg into a round hole.

Upon closer examination, I realized that what ab-glyph _does_ provide APIs for are the global font metrics like [ascent](https://docs.rs/ab_glyph/0.2.15/ab_glyph/trait.Font.html#tymethod.ascent_unscaled).

So the solution that's working for my set of cases now involves only a few simple subtraction operations using what metrics _are_ provided in the ab-glyph API: especially calculating the difference between the font's `ascent` and a glyph's `y_min` from the bounds rect provided by ab-glyph's [px_bounds()](https://docs.rs/ab_glyph/0.2.15/ab_glyph/struct.OutlinedGlyph.html#method.px_bounds). I was able to use similar horizontal properties from `px_bounds()` to get the horizontal position right as well.

So all of my test cases are now working as expected, which includes some re-positioning vertically (both up and down) and horizontally (both left and right). It has not required computing any tight bboxes.

This makes me think that perhaps this is what harfbuzz and the others are up to [when they're doing shaping](https://harfbuzz.github.io/why-do-i-need-a-shaping-engine.html). (I have very little familiarity with shaping, per se. This conversation has been eye-opening). I can appreciate that solving for positioning like this in the general case of all possibilities involving various horizontal and vertical metrics encoded in a font would be much more complicated. Fortunately, my particular use cases are much more constrained, so these simple calculations seem to be doing all of the shaping and/or positioning necessary at the moment.

Thanks again.

**Comment by RazrFalcon** [comment]
Glad to hear. rustybuzz is 20 KLOC (+12.5 KLOC of ttf-parser), so it's much more complicated than simply doing a few "subtraction operations".

As for `ascent`, ab-glyph [simply calls](https://github.com/alexheretic/ab-glyph/blob/c4256676c27c6b371b734f046b08472907a8e02d/glyph/src/ttfp.rs#L194) ttf-parser method here, afaik. Which in itself is famously [a nightmare](https://github.com/freetype/freetype/blob/49270c17011491227ec7bd3fb73ede4f674aa065/src/sfnt/sfobjs.c#L1279). It can be defined in three different places in the font, two of which are affected by variation axes (in case of a variable font).

Once again, I'm not sure what is your goal, but for getting glyph metrics you can look into: `ascender`, `descender`, `glyph_hor_advance` and `glyph_hor_side_bearing` methods of the `Face` type. The last two are optional.

**Comment by mlwilkerson** [comment]
In my case, what I'm testing is my own font builder. So one of my test expectations is that the font builder has encoded that `ascent` in a way that will work reliably. If I found that these tests were breaking because of something strange happening with resolving that `ascent` from the font, such as by ab-glyph's call into ttf-parser, I think it might point toward a bug in how the font builder encoded it in the font being tested, which would be a valuable test failure pointing toward a bug in the font builder under test.
