### ISSUE TITLE
Nunito-VariableFont_wght.ttf glyph_hor_side_bearing = `None` 

### ISSUE THREAD

**Issue by alexheretic** [RazrFalcon/ttf-parser#98]
Issue with _Nunito-VariableFont_wght.ttf_ (https://fonts.google.com/specimen/Nunito) calling `glyph_hor_side_bearing` for all glyphs returns `None` which is not the behaviour _ab_glyph_ expects currently.

## Example
```rust
let face = ttf_parser::Face::from_slice(include_bytes!("../Nunito-VariableFont_wght.ttf"), 0).unwrap();

eprintln!(
    "glyph_hor_side_bearing(567) = {:?}",
    face.glyph_hor_side_bearing(ttf_parser::GlyphId(567))
);
// glyph_hor_side_bearing(567) = None
```

The cause seems to be that the hvar table has `lsb_mapping_offset = None`. This causes `hvar.side_bearing_offset` & `face.glyph_hor_side_bearing` to return `None` as this is a variable font.

Since the hmtx.side_bearing _does_ exist this seems the wrong behaviour.

Downstream: https://github.com/alexheretic/ab-glyph/issues/62

**Comment by RazrFalcon** [comment]
Yes, I should not bail immediately when querying HVAR/VVAR.

**Comment by RazrFalcon** [comment]
Published a new version.

**Comment by alexheretic** [comment]
Thanks for looking at this so quickly :+1:
